name: Generate Wrapper

on:
  workflow_dispatch:

jobs:
  wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - run: gradle wrapper --gradle-version 8.9
      - run: git add gradlew gradlew.bat gradle/wrapper && git commit -m "Add Gradle wrapper" || echo "No changes"
      - run: git push